---
name: Destroy GitHub Runner

on:
  workflow_dispatch:

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: "Destroy GitHub Runner"
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    defaults:
      run:
        working-directory: code/terraform/github-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: "${{ env.AWS_ROLE_ARN }}"
          role-session-name: dfr-tfm-terraform-destroy-github-runner
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 22.3.0

      - name: Set up Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8
        with:
          terraform_version: "1.8.5"

      - name: Terraform init
        id: init
        run: terraform init -no-color

      - name: Terraform destroy
        id: destroy
        run: |
          export TF_VAR_gh_pat="${{ env.GH_PAT }}"
          terraform destroy -auto-approve -no-color
