---
name: Terraform Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths:
      - 'code/terraform/**/*.tf'

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  CHECKOV_SKIP_CHECKS: ${{ vars.CHECKOV_SKIP_CHECKS }}

permissions:
  id-token: write
  contents: read

jobs:
  ValidateTerraform:
    name: "Terraform Validation"
    runs-on: self-hosted
    timeout-minutes: 30
    strategy:
      matrix:
        project: [
          nextcloud,
          github-runner,
          oidc-github-actions/iam_role,
          oidc-github-actions/identity_provider,
          cognito-group,
          cognito-users
        ]
    defaults:
      run:
        working-directory: code/terraform/${{ matrix.project }}

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: "${{ env.AWS_ROLE_ARN }}"
          role-session-name: "dfr-tfm-terraform-validate-terraform"
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 22.3.0

      - name: Set up Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8
        with:
          terraform_version: "1.8.5"

      - name: Terraform format
        id: fmt
        run: terraform fmt -check -no-color

      - name: Terraform init
        id: init
        run: terraform init -no-color

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf
        with:
          directory: code/terraform/${{ matrix.project }}
          framework: terraform
          skip_check: ${{ env.CHECKOV_SKIP_CHECKS }}
          download_external_modules: true
