---
name: 'Shell Check'

on:
  pull_request:
    paths:
      - '**/*.sh'

env:
  GH_PAT: ${{ secrets.GH_PAT }}

permissions:
  contents: read

jobs:
  shellcheck:
    name: 'Shell Check'
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: 'Shell Check'
        id: shellcheck
        uses: sudo-bot/action-shellcheck@latest
        with:
          cli-args: "**/*.sh --severity=warning"
