---
name: 'YAML Lint'

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

env:
  GH_PAT: ${{ secrets.GH_PAT }}

permissions:
  contents: read

jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@fdef6bc189425ecc84cc4543b2674566c0827053
        with:
          yamllint_config_filepath: .yamllint
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ env.GH_PAT }}
