---
name: 'Validate Python code'

on:
  pull_request:
    paths:
      - '**/*py'

permissions:
  contents: read

jobs:
  pythonlint:
    name: 'Python Lint'
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        id: python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
        with:
          python-version: '3.10.12'

      - name: Run Python black
        id: black
        uses: psf/black@b965c2a5026f8ba399283ba3e01898b012853c79
        with:
          options: "--check --verbose"
          version: "24.8.0"
